### PR TITLE
MIST-569 Go Component Tests/Pre-Commit Hooks

### PR DESCRIPTION
**Pull request by bbickerton**
Getting existing tests to pass. Using Jenkins to run the tests.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent-libvirt/22)

### CODE REVIEW

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by rizvfe00** [comment]
Ok to test

**Comment by mmlb** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[libvirt_test.go, line 41 \[r5\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/22#-K5qY-Mi5-Wx8PoZkYb2:-K5qY-Mi5-Wx8PoZkYb3:-392387649) ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/44dc0a5ae57b759039363b00e071dbc7a59b8730/libvirt_test.go#L41)):*
FYI Should we put up this image into our own s3 bucket? This way we don't cause too much network traffic to qemu.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/22)*

**Comment by mmlb** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/22)*

**Comment by TauZero** [comment]
Ok to test

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/22)*

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[libvirt_test.go, line 41 \[r5\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/22#-K5qY-Mi5-Wx8PoZkYb2:-K5qavYbfmhOj70696mz:-499146009) ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/44dc0a5ae57b759039363b00e071dbc7a59b8730/libvirt_test.go#L41)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/22)*

**Pull request merged**
