### PR TITLE
MIST-559 Cleanup for linting, etc.

### PR DESCRIPTION
**Pull request by TauZero**
Some changes related to cleanup in mistify-agent

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent-libvirt/20)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 3 of 3 files at r4, 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/20)

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by rizvfe00** [comment]
Ok to test

**Comment by rizvfe00** [comment]
Ok to test

**Comment by rizvfe00** [comment]
Ok to test

**Comment by rizvfe00** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/20)

**Comment by rizvfe00** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
AWS doesn't do well with libvirt stuff. After offline discussion, going to merge this since it has changes necessary for use with mistify-agent master. We'll deal with any missed issues that crop up in the next full integration test.

**Pull request merged**
