### PR TITLE
Go kvm lxc testing

### PR DESCRIPTION
**Pull request by omniti-devops**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent-libvirt/21)

### CODE REVIEW

**Comment by TauZero** [comment]
Reviewed 2 of 12 files at r1.
Review status: 2 of 12 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[test/provisioning/inventories/local, line 0 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sPvQ5NsYJImuZFqbv)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/inventories/local#L0)):</sup>
Is this just to make sure the directory exists? Any way to check for existence and the dir with the scripts instead?


---

<sup>**[test/provisioning/vars/dummy, line 0 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sP_qQMdV2DMsFA1P2)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/vars/dummy#L0)):</sup>
Is this just to make sure the directory exists? Any way to check for existence and the dir with the scripts instead?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21)

**Comment by TauZero** [comment]
Reviewed 7 of 12 files at r1.
Review status: 9 of 12 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[test/provisioning/group_vars/all, line 1 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sRutadX2FFGE3Esf2)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/group_vars/all#L1)):</sup>
Can we take out our specific jenkins url, git username, git usermail rather than having them in the repo?


---

<sup>**[test/provisioning/provision-container.yml, line 18 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sS_JY0zvZzkiyPJel)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/provision-container.yml#L18)):</sup>
Are all of these keys necessary? Particularly the two yoni@ entries.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21)

**Comment by mmlb** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[test/provisioning/.kitchen.yml, line 20 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sa0-1_9SHOa00Ylyz)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/.kitchen.yml#L20)):</sup>
Should we switch this out to a different box since chef/ubuntu was move to a new location? Either use bento/ubuntu-14.04 or ubuntu/trusty64?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21)

**Comment by rizvfe00** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[test/provisioning/.kitchen.yml, line 20 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sa0-1_9SHOa00Ylyz)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/.kitchen.yml#L20)):</sup>
Using kitchen-ansible is a little wonky for this because we use the python script to download our custom roles from the infrastructure jenkins slave repo. 

 I am removing the test kitchen setup for now when we put something in place like librarian-ansible and refactor out those roles from the jenkins slave repo, we can probably remove the python script and add in test-kitchen again.

I already started refactoring the jenkins slave roles to make them more portable.


---

<sup>**[test/provisioning/group_vars/all, line 1 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sRutadX2FFGE3Esf2)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/group_vars/all#L1)):</sup>
 The jenkins url can be removed.  The git username, e-mail need to be provided somehow,  it makes the most sense inside group vars but we could generate it at build time.  That would make it harder to run the tests locally though.  Maybe we should talk about whether this test setup belongs inside the mistify-agent-libvirt repo or in a private repo by itself?


---

<sup>**[test/provisioning/inventories/local, line 0 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sPvQ5NsYJImuZFqbv)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/inventories/local#L0)):</sup>
 Used during local dev, removed.


---

<sup>**[test/provisioning/provision-container.yml, line 18 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sS_JY0zvZzkiyPJel)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/provision-container.yml#L18)):</sup>
 Short answer both are not required.

 It's actually 2 keys being added to authorized_keys for root once and the ubuntu user once.  We create the container then use Ansible (ssh) to provision the container using both users and run the tests.

 Since the tests run on Dev2 the private key on there is yoni's (hence the pub key in authorized keys) and terraform.pem is the default key we use for jenkins slaves (also the one I use for local testing).

 I can copy down yoni's key or put the terraform private key on Dev2 to remove one of the keys.


---

<sup>**[test/provisioning/vars/dummy, line 0 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sP_qQMdV2DMsFA1P2)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/vars/dummy#L0)):</sup>
Yes, just to make sure the directory exists, the vars dir is part of Ansible's standard directory structure.  I added the code to the python script to create the dir instead.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21)

**Comment by TauZero** [comment]
Reviewed 1 of 8 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[test/provisioning/group_vars/all, line 0 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sRutadX2FFGE3Esf2)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/group_vars/all#L0)):</sup>
Might be worth pulling it out into a private repo. Keeps mistify-agent-libvirt clean and simple and lets us tailor the test setup to our specific build environment, which wouldn't be relevant to the general community.


---

<sup>**[test/provisioning/provision-container.yml, line 18 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sS_JY0zvZzkiyPJel)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/provision-container.yml#L18)):</sup>
I see. This is some pretty specific stuff to our testing environment. I don't know if we want it in the repo if we keep this in mistify-agent-libvirt.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21)

**Comment by rizvfe00** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[test/provisioning/group_vars/all, line 0 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sRutadX2FFGE3Esf2)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/group_vars/all#L0)):</sup>
Okay, I think that might be a good idea.  I'll talk to Steven about maybe placing this stuff into mistify-test or creating a seperate repo entirely.


---

<sup>**[test/provisioning/provision-container.yml, line 18 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21#-K-sS_JY0zvZzkiyPJel)** ([raw file](https://github.com/mistifyio/mistify-agent-libvirt/blob/6a45f2f77759de07030afe600216eced5d56bd22/test/provisioning/provision-container.yml#L18)):</sup>
I'll look into removing one of them, if this goes into a private repo, it becomes less of a concern


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent-libvirt/21)

**Comment by TauZero** [comment]
Just to close the loop, this functionality is being moved out of the `mistify-agent-libvirt` repo to another location.

**Pull request closed without merging**
